# apiVersion: v1
# kind: Secret
# metadata:
#   name: {{ .Values.kubernetes.namespace.app }}-db-secrets
#   namespace: {{ .Values.kubernetes.namespace.app }}
# type: Opaque
# data:
#   DB_USERNAME: {{ .Values.database.username | b64enc }}
#   DB_PASSWORD: {{ .Values.database.password | b64enc }}
---
apiVersion: v1
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSIxNDc5MDczNjg4NDUuZGtyLmVjci51cy1lYXN0LTEuYW1hem9uYXdzLmNvbSI6IHt9LAoJCSIzMTU5NjI4ODI4MjIuZGtyLmVjci51cy1lYXN0LTEuYW1hem9uYXdzLmNvbSI6IHt9LAoJCSI0MzY5Mzc2MTQ0ODIuZGtyLmVjci5jbi1ub3J0aC0xLmFtYXpvbmF3cy5jb20uY24iOiB7fSwKCQkiODE5ODk1MjQxMzE5LmRrci5lY3IuYXAtc291dGhlYXN0LTEuYW1hem9uYXdzLmNvbSI6IHt9LAoJCSI4MTk4OTUyNDEzMTkuZGtyLmVjci51cy1lYXN0LTEuYW1hem9uYXdzLmNvbSI6IHt9LAoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJhSFY1Ym1oa2JtZDFlV1Z1T21kb2NGODRWRnBrY0ZCSFRURkNSVXRKYXpKeVJUUkJXV1ZuVEU5V2IybGxkV013YVV0eE5Hbz0iCgkJfQoJfSwKCSJjdXJyZW50Q29udGV4dCI6ICJkZXNrdG9wLWxpbnV4IiwKCSJwbHVnaW5zIjogewoJCSIteC1jbGktaGludHMiOiB7CgkJCSJlbmFibGVkIjogInRydWUiCgkJfSwKCQkiZGVidWciOiB7CgkJCSJob29rcyI6ICJleGVjIgoJCX0sCgkJInNjb3V0IjogewoJCQkiaG9va3MiOiAicHVsbCxidWlsZHggYnVpbGQiCgkJfQoJfSwKCSJmZWF0dXJlcyI6IHsKCQkiaG9va3MiOiAidHJ1ZSIKCX0KfQ==
kind: Secret
metadata:
  name: ghcr-secret
  namespace: app
type: kubernetes.io/dockerconfigjson
